- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: false
  objective: roles-antag-space-ninja-objective
  guides: [ SpaceNinja ]

#Ninja Gear
- type: startingGear
  id: SpaceNinjaGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    back: ClothingBackpackSpaceNinja # SS220 Ninja Resprite
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinja
    id: AgentIDCard
    ears: ClothingHeadsetGrey
    pocket1: DoubleEmergencyOxygenTankFilled # SS220 Ninja Resprite
    pocket2: PinpointerStation
    belt: EnergyKatana
  inhand:
    - JetpackBlackFilled
  storage:
    back: # belt holds katana so satchel has the tools for sabotaging things
    - Crowbar
    - Wrench
    - Screwdriver
    - Wirecutter
    - Welder
    - Multitool
    - BoxSurvivalEngineering # SS220 Ninja Resprite

- type: chameleonOutfit
  id: NinjaChameleonOutfit
  name: roles-antag-space-ninja-name
  startingGear: SpaceNinjaGear
  equipment:
    id: PassengerPDA
    neck: ClothingNeckGoldmedal
